# Generated by Django 4.2.28 on 2026-03-31 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeter_pages', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_twits', to=settings.AUTH_USER_MODEL),
        ),
    ]
